namespace KpInfohelp.Reports
{
    partial class rptKwitDB
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery1 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column1 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression1 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table1 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column2 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression2 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column3 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression3 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column4 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression4 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column5 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression5 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column6 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression6 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column7 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression7 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column8 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression8 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column9 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression9 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column10 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression10 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column11 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression11 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column12 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression12 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column13 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression13 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column14 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression14 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column15 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression15 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column16 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression16 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column17 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression17 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column18 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression18 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery2 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column19 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression19 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table2 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column20 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression20 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column21 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression21 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column22 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression22 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column23 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression23 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column24 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression24 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column25 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression25 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column26 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression26 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column27 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression27 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column28 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression28 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column29 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression29 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column30 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression30 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column31 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression31 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column32 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression32 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column33 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression33 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column34 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression34 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column35 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression35 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column36 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression36 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column37 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression37 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column38 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression38 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery3 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column39 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression39 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table3 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column40 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression40 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column41 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression41 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column42 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression42 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column43 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression43 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column44 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression44 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column45 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression45 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column46 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression46 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column47 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression47 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column48 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression48 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column49 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression49 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column50 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression50 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column51 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression51 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column52 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression52 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table4 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column53 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression53 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column54 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression54 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column55 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression55 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column56 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression56 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column57 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression57 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column58 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression58 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column59 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression59 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column60 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression60 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column61 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression61 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column62 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression62 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column63 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression63 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column64 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression64 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column65 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression65 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column66 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression66 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column67 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression67 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column68 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression68 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column69 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression69 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column70 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression70 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column71 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression71 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column72 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression72 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table5 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column73 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression73 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column74 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression74 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column75 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression75 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column76 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression76 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column77 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression77 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table6 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column78 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression78 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column79 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression79 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column80 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression80 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column81 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression81 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table7 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column82 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression82 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column83 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression83 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column84 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression84 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column85 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression85 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column86 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression86 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column87 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression87 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column88 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression88 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column89 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression89 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column90 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression90 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column91 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression91 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column92 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression92 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column93 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression93 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Join join1 = new DevExpress.DataAccess.Sql.Join();
            DevExpress.DataAccess.Sql.RelationColumnInfo relationColumnInfo1 = new DevExpress.DataAccess.Sql.RelationColumnInfo();
            DevExpress.DataAccess.Sql.Join join2 = new DevExpress.DataAccess.Sql.Join();
            DevExpress.DataAccess.Sql.RelationColumnInfo relationColumnInfo2 = new DevExpress.DataAccess.Sql.RelationColumnInfo();
            DevExpress.DataAccess.Sql.Join join3 = new DevExpress.DataAccess.Sql.Join();
            DevExpress.DataAccess.Sql.RelationColumnInfo relationColumnInfo3 = new DevExpress.DataAccess.Sql.RelationColumnInfo();
            DevExpress.DataAccess.Sql.Join join4 = new DevExpress.DataAccess.Sql.Join();
            DevExpress.DataAccess.Sql.RelationColumnInfo relationColumnInfo4 = new DevExpress.DataAccess.Sql.RelationColumnInfo();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery4 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column94 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression94 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table8 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column95 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression95 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column96 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression96 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column97 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression97 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery5 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column98 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression98 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table9 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column99 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression99 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column100 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression100 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column101 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression101 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column102 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression102 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column103 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression103 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column104 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression104 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column105 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression105 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column106 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression106 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column107 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression107 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column108 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression108 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column109 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression109 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column110 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression110 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery6 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column111 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression111 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table10 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column112 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression112 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column113 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression113 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery7 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column114 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression114 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table11 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column115 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression115 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column116 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression116 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column117 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression117 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column118 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression118 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.SelectQuery selectQuery8 = new DevExpress.DataAccess.Sql.SelectQuery();
            DevExpress.DataAccess.Sql.Column column119 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression119 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table12 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column120 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression120 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column121 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression121 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column122 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression122 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column123 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression123 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column124 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression124 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column125 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression125 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column126 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression126 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column127 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression127 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column128 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression128 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column129 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression129 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column130 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression130 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column131 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression131 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column132 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression132 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table13 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column133 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression133 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column134 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression134 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column135 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression135 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column136 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression136 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table14 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column137 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression137 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column138 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression138 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column139 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression139 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column140 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression140 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column141 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression141 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column142 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression142 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column143 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression143 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column144 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression144 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column145 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression145 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column146 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression146 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column147 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression147 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column148 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression148 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column149 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression149 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column150 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression150 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column151 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression151 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column152 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression152 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column153 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression153 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column154 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression154 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column155 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression155 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column156 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression156 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Table table15 = new DevExpress.DataAccess.Sql.Table();
            DevExpress.DataAccess.Sql.Column column157 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression157 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column158 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression158 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column159 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression159 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column160 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression160 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column161 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression161 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column162 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression162 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column163 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression163 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column164 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression164 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column165 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression165 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column166 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression166 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column167 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression167 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.Column column168 = new DevExpress.DataAccess.Sql.Column();
            DevExpress.DataAccess.Sql.ColumnExpression columnExpression168 = new DevExpress.DataAccess.Sql.ColumnExpression();
            DevExpress.DataAccess.Sql.QueryParameter queryParameter1 = new DevExpress.DataAccess.Sql.QueryParameter();
            DevExpress.DataAccess.Sql.Join join5 = new DevExpress.DataAccess.Sql.Join();
            DevExpress.DataAccess.Sql.RelationColumnInfo relationColumnInfo5 = new DevExpress.DataAccess.Sql.RelationColumnInfo();
            DevExpress.DataAccess.Sql.Join join6 = new DevExpress.DataAccess.Sql.Join();
            DevExpress.DataAccess.Sql.RelationColumnInfo relationColumnInfo6 = new DevExpress.DataAccess.Sql.RelationColumnInfo();
            DevExpress.DataAccess.Sql.Join join7 = new DevExpress.DataAccess.Sql.Join();
            DevExpress.DataAccess.Sql.RelationColumnInfo relationColumnInfo7 = new DevExpress.DataAccess.Sql.RelationColumnInfo();
            DevExpress.DataAccess.Sql.MasterDetailInfo masterDetailInfo1 = new DevExpress.DataAccess.Sql.MasterDetailInfo();
            DevExpress.DataAccess.Sql.RelationColumnInfo relationColumnInfo8 = new DevExpress.DataAccess.Sql.RelationColumnInfo();
            DevExpress.DataAccess.Sql.MasterDetailInfo masterDetailInfo2 = new DevExpress.DataAccess.Sql.MasterDetailInfo();
            DevExpress.DataAccess.Sql.RelationColumnInfo relationColumnInfo9 = new DevExpress.DataAccess.Sql.RelationColumnInfo();
            DevExpress.DataAccess.Sql.MasterDetailInfo masterDetailInfo3 = new DevExpress.DataAccess.Sql.MasterDetailInfo();
            DevExpress.DataAccess.Sql.RelationColumnInfo relationColumnInfo10 = new DevExpress.DataAccess.Sql.RelationColumnInfo();
            DevExpress.DataAccess.Sql.MasterDetailInfo masterDetailInfo4 = new DevExpress.DataAccess.Sql.MasterDetailInfo();
            DevExpress.DataAccess.Sql.RelationColumnInfo relationColumnInfo11 = new DevExpress.DataAccess.Sql.RelationColumnInfo();
            DevExpress.DataAccess.Sql.MasterDetailInfo masterDetailInfo5 = new DevExpress.DataAccess.Sql.MasterDetailInfo();
            DevExpress.DataAccess.Sql.RelationColumnInfo relationColumnInfo12 = new DevExpress.DataAccess.Sql.RelationColumnInfo();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(rptKwitDB));
            this.Detail = new DevExpress.XtraReports.UI.DetailBand();
            this.TopMargin = new DevExpress.XtraReports.UI.TopMarginBand();
            this.BottomMargin = new DevExpress.XtraReports.UI.BottomMarginBand();
            this.sqlDataSource1 = new DevExpress.DataAccess.Sql.SqlDataSource(this.components);
            this.DetailReport = new DevExpress.XtraReports.UI.DetailReportBand();
            this.Detail1 = new DevExpress.XtraReports.UI.DetailBand();
            this.xrLabel1 = new DevExpress.XtraReports.UI.XRLabel();
            this.xrLabel2 = new DevExpress.XtraReports.UI.XRLabel();
            this.xrLabel3 = new DevExpress.XtraReports.UI.XRLabel();
            this.xrLabel4 = new DevExpress.XtraReports.UI.XRLabel();
            this.xrLabel5 = new DevExpress.XtraReports.UI.XRLabel();
            this.xrLabel6 = new DevExpress.XtraReports.UI.XRLabel();
            this.xrLabel7 = new DevExpress.XtraReports.UI.XRLabel();
            ((System.ComponentModel.ISupportInitialize)(this)).BeginInit();
            // 
            // Detail
            // 
            this.Detail.Controls.AddRange(new DevExpress.XtraReports.UI.XRControl[] {
            this.xrLabel7,
            this.xrLabel6,
            this.xrLabel5});
            this.Detail.HeightF = 78.20835F;
            this.Detail.Name = "Detail";
            this.Detail.Padding = new DevExpress.XtraPrinting.PaddingInfo(0, 0, 0, 0, 100F);
            this.Detail.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopLeft;
            // 
            // TopMargin
            // 
            this.TopMargin.HeightF = 0F;
            this.TopMargin.Name = "TopMargin";
            this.TopMargin.Padding = new DevExpress.XtraPrinting.PaddingInfo(0, 0, 0, 0, 100F);
            this.TopMargin.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopLeft;
            // 
            // BottomMargin
            // 
            this.BottomMargin.HeightF = 100F;
            this.BottomMargin.Name = "BottomMargin";
            this.BottomMargin.Padding = new DevExpress.XtraPrinting.PaddingInfo(0, 0, 0, 0, 100F);
            this.BottomMargin.TextAlignment = DevExpress.XtraPrinting.TextAlignment.TopLeft;
            // 
            // sqlDataSource1
            // 
            this.sqlDataSource1.ConnectionName = "infohelp\\sqlexpress.INFOHELP.dbo";
            this.sqlDataSource1.Name = "sqlDataSource1";
            columnExpression1.ColumnName = "ID_IHP_KONTRAHENT";
            table1.Name = "IHP_KONTRAHENT";
            columnExpression1.Table = table1;
            column1.Expression = columnExpression1;
            columnExpression2.ColumnName = "NRKONTRAH";
            columnExpression2.Table = table1;
            column2.Expression = columnExpression2;
            columnExpression3.ColumnName = "NIP";
            columnExpression3.Table = table1;
            column3.Expression = columnExpression3;
            columnExpression4.ColumnName = "NAZWA";
            columnExpression4.Table = table1;
            column4.Expression = columnExpression4;
            columnExpression5.ColumnName = "MIEJSCOWOSC";
            columnExpression5.Table = table1;
            column5.Expression = columnExpression5;
            columnExpression6.ColumnName = "KODPOCZTOWY";
            columnExpression6.Table = table1;
            column6.Expression = columnExpression6;
            columnExpression7.ColumnName = "POCZTA";
            columnExpression7.Table = table1;
            column7.Expression = columnExpression7;
            columnExpression8.ColumnName = "ULICA";
            columnExpression8.Table = table1;
            column8.Expression = columnExpression8;
            columnExpression9.ColumnName = "NRDOMU";
            columnExpression9.Table = table1;
            column9.Expression = columnExpression9;
            columnExpression10.ColumnName = "NRLOKALU";
            columnExpression10.Table = table1;
            column10.Expression = columnExpression10;
            columnExpression11.ColumnName = "EMAIL";
            columnExpression11.Table = table1;
            column11.Expression = columnExpression11;
            columnExpression12.ColumnName = "TELEFON";
            columnExpression12.Table = table1;
            column12.Expression = columnExpression12;
            columnExpression13.ColumnName = "ID_IHP_DEFCENY";
            columnExpression13.Table = table1;
            column13.Expression = columnExpression13;
            columnExpression14.ColumnName = "ID_KH_SUBJECT";
            columnExpression14.Table = table1;
            column14.Expression = columnExpression14;
            columnExpression15.ColumnName = "TELKOM";
            columnExpression15.Table = table1;
            column15.Expression = columnExpression15;
            columnExpression16.ColumnName = "TYPKONTRAH";
            columnExpression16.Table = table1;
            column16.Expression = columnExpression16;
            columnExpression17.ColumnName = "NAZWAPELNA";
            columnExpression17.Table = table1;
            column17.Expression = columnExpression17;
            columnExpression18.ColumnName = "ID_IHP_RODZAJDOKDEF";
            columnExpression18.Table = table1;
            column18.Expression = columnExpression18;
            selectQuery1.Columns.Add(column1);
            selectQuery1.Columns.Add(column2);
            selectQuery1.Columns.Add(column3);
            selectQuery1.Columns.Add(column4);
            selectQuery1.Columns.Add(column5);
            selectQuery1.Columns.Add(column6);
            selectQuery1.Columns.Add(column7);
            selectQuery1.Columns.Add(column8);
            selectQuery1.Columns.Add(column9);
            selectQuery1.Columns.Add(column10);
            selectQuery1.Columns.Add(column11);
            selectQuery1.Columns.Add(column12);
            selectQuery1.Columns.Add(column13);
            selectQuery1.Columns.Add(column14);
            selectQuery1.Columns.Add(column15);
            selectQuery1.Columns.Add(column16);
            selectQuery1.Columns.Add(column17);
            selectQuery1.Columns.Add(column18);
            selectQuery1.MetaSerializable = "<Meta X=\"20\" Y=\"20\" Width=\"100\" Height=\"343\" />";
            selectQuery1.Name = "IHP_KONTRAHENT";
            selectQuery1.Tables.Add(table1);
            columnExpression19.ColumnName = "ID_IHP_KONTRAHENT_ARCH";
            table2.Name = "IHP_KONTRAHENT_ARCH";
            columnExpression19.Table = table2;
            column19.Expression = columnExpression19;
            columnExpression20.ColumnName = "ID_IHP_KONTRAHENT";
            columnExpression20.Table = table2;
            column20.Expression = columnExpression20;
            columnExpression21.ColumnName = "NRKONTRAH";
            columnExpression21.Table = table2;
            column21.Expression = columnExpression21;
            columnExpression22.ColumnName = "NIP";
            columnExpression22.Table = table2;
            column22.Expression = columnExpression22;
            columnExpression23.ColumnName = "NAZWA";
            columnExpression23.Table = table2;
            column23.Expression = columnExpression23;
            columnExpression24.ColumnName = "MIEJSCOWOSC";
            columnExpression24.Table = table2;
            column24.Expression = columnExpression24;
            columnExpression25.ColumnName = "KODPOCZTOWY";
            columnExpression25.Table = table2;
            column25.Expression = columnExpression25;
            columnExpression26.ColumnName = "POCZTA";
            columnExpression26.Table = table2;
            column26.Expression = columnExpression26;
            columnExpression27.ColumnName = "ULICA";
            columnExpression27.Table = table2;
            column27.Expression = columnExpression27;
            columnExpression28.ColumnName = "NRDOMU";
            columnExpression28.Table = table2;
            column28.Expression = columnExpression28;
            columnExpression29.ColumnName = "NRLOKALU";
            columnExpression29.Table = table2;
            column29.Expression = columnExpression29;
            columnExpression30.ColumnName = "EMAIL";
            columnExpression30.Table = table2;
            column30.Expression = columnExpression30;
            columnExpression31.ColumnName = "TELEFON";
            columnExpression31.Table = table2;
            column31.Expression = columnExpression31;
            columnExpression32.ColumnName = "AKTYWNY";
            columnExpression32.Table = table2;
            column32.Expression = columnExpression32;
            columnExpression33.ColumnName = "ID_IHP_DEFCENY";
            columnExpression33.Table = table2;
            column33.Expression = columnExpression33;
            columnExpression34.ColumnName = "ID_KH_SUBJECT";
            columnExpression34.Table = table2;
            column34.Expression = columnExpression34;
            columnExpression35.ColumnName = "TELKOM";
            columnExpression35.Table = table2;
            column35.Expression = columnExpression35;
            columnExpression36.ColumnName = "TYPKONTRAH";
            columnExpression36.Table = table2;
            column36.Expression = columnExpression36;
            columnExpression37.ColumnName = "NAZWAPELNA";
            columnExpression37.Table = table2;
            column37.Expression = columnExpression37;
            columnExpression38.ColumnName = "ID_IHP_RODZAJDOKDEF";
            columnExpression38.Table = table2;
            column38.Expression = columnExpression38;
            selectQuery2.Columns.Add(column19);
            selectQuery2.Columns.Add(column20);
            selectQuery2.Columns.Add(column21);
            selectQuery2.Columns.Add(column22);
            selectQuery2.Columns.Add(column23);
            selectQuery2.Columns.Add(column24);
            selectQuery2.Columns.Add(column25);
            selectQuery2.Columns.Add(column26);
            selectQuery2.Columns.Add(column27);
            selectQuery2.Columns.Add(column28);
            selectQuery2.Columns.Add(column29);
            selectQuery2.Columns.Add(column30);
            selectQuery2.Columns.Add(column31);
            selectQuery2.Columns.Add(column32);
            selectQuery2.Columns.Add(column33);
            selectQuery2.Columns.Add(column34);
            selectQuery2.Columns.Add(column35);
            selectQuery2.Columns.Add(column36);
            selectQuery2.Columns.Add(column37);
            selectQuery2.Columns.Add(column38);
            selectQuery2.MetaSerializable = "<Meta X=\"40\" Y=\"360\" Width=\"280\" Height=\"377\" />";
            selectQuery2.Name = "IHP_KONTRAHENT_ARCH";
            selectQuery2.Tables.Add(table2);
            columnExpression39.ColumnName = "ID_IHP_WAZENIE";
            table3.Name = "IHP_WAZENIE";
            columnExpression39.Table = table3;
            column39.Expression = columnExpression39;
            columnExpression40.ColumnName = "DATAWJAZD";
            columnExpression40.Table = table3;
            column40.Expression = columnExpression40;
            columnExpression41.ColumnName = "DATAWYJAZD";
            columnExpression41.Table = table3;
            column41.Expression = columnExpression41;
            columnExpression42.ColumnName = "ID_IHP_KIEROWCA";
            columnExpression42.Table = table3;
            column42.Expression = columnExpression42;
            columnExpression43.ColumnName = "ID_IHP_SAMOCHOD";
            columnExpression43.Table = table3;
            column43.Expression = columnExpression43;
            columnExpression44.ColumnName = "WAGAWJAZD";
            columnExpression44.Table = table3;
            column44.Expression = columnExpression44;
            columnExpression45.ColumnName = "WAGAWYJAZD";
            columnExpression45.Table = table3;
            column45.Expression = columnExpression45;
            columnExpression46.ColumnName = "ID_IHP_KONTRAHENT_ARCH";
            columnExpression46.Table = table3;
            column46.Expression = columnExpression46;
            columnExpression47.ColumnName = "ID_IHP_KARTOTEKA";
            columnExpression47.Table = table3;
            column47.Expression = columnExpression47;
            columnExpression48.ColumnName = "ID_IHP_RODZAJDOK";
            columnExpression48.Table = table3;
            column48.Expression = columnExpression48;
            columnExpression49.ColumnName = "STATUS";
            columnExpression49.Table = table3;
            column49.Expression = columnExpression49;
            columnExpression50.ColumnName = "NRKWIT";
            columnExpression50.Table = table3;
            column50.Expression = columnExpression50;
            columnExpression51.ColumnName = "NRKWITWEW";
            columnExpression51.Table = table3;
            column51.Expression = columnExpression51;
            column52.Alias = "IHP_KONTRAHENT_ARCH_ID_IHP_KONTRAHENT_ARCH";
            columnExpression52.ColumnName = "ID_IHP_KONTRAHENT_ARCH";
            table4.Name = "IHP_KONTRAHENT_ARCH";
            columnExpression52.Table = table4;
            column52.Expression = columnExpression52;
            columnExpression53.ColumnName = "ID_IHP_KONTRAHENT";
            columnExpression53.Table = table4;
            column53.Expression = columnExpression53;
            columnExpression54.ColumnName = "NRKONTRAH";
            columnExpression54.Table = table4;
            column54.Expression = columnExpression54;
            columnExpression55.ColumnName = "NIP";
            columnExpression55.Table = table4;
            column55.Expression = columnExpression55;
            columnExpression56.ColumnName = "NAZWA";
            columnExpression56.Table = table4;
            column56.Expression = columnExpression56;
            columnExpression57.ColumnName = "MIEJSCOWOSC";
            columnExpression57.Table = table4;
            column57.Expression = columnExpression57;
            columnExpression58.ColumnName = "KODPOCZTOWY";
            columnExpression58.Table = table4;
            column58.Expression = columnExpression58;
            columnExpression59.ColumnName = "POCZTA";
            columnExpression59.Table = table4;
            column59.Expression = columnExpression59;
            columnExpression60.ColumnName = "ULICA";
            columnExpression60.Table = table4;
            column60.Expression = columnExpression60;
            columnExpression61.ColumnName = "NRDOMU";
            columnExpression61.Table = table4;
            column61.Expression = columnExpression61;
            columnExpression62.ColumnName = "NRLOKALU";
            columnExpression62.Table = table4;
            column62.Expression = columnExpression62;
            columnExpression63.ColumnName = "EMAIL";
            columnExpression63.Table = table4;
            column63.Expression = columnExpression63;
            columnExpression64.ColumnName = "TELEFON";
            columnExpression64.Table = table4;
            column64.Expression = columnExpression64;
            columnExpression65.ColumnName = "AKTYWNY";
            columnExpression65.Table = table4;
            column65.Expression = columnExpression65;
            columnExpression66.ColumnName = "ID_IHP_DEFCENY";
            columnExpression66.Table = table4;
            column66.Expression = columnExpression66;
            columnExpression67.ColumnName = "ID_KH_SUBJECT";
            columnExpression67.Table = table4;
            column67.Expression = columnExpression67;
            columnExpression68.ColumnName = "TELKOM";
            columnExpression68.Table = table4;
            column68.Expression = columnExpression68;
            columnExpression69.ColumnName = "TYPKONTRAH";
            columnExpression69.Table = table4;
            column69.Expression = columnExpression69;
            columnExpression70.ColumnName = "NAZWAPELNA";
            columnExpression70.Table = table4;
            column70.Expression = columnExpression70;
            columnExpression71.ColumnName = "ID_IHP_RODZAJDOKDEF";
            columnExpression71.Table = table4;
            column71.Expression = columnExpression71;
            column72.Alias = "IHP_SAMOCHOD_ID_IHP_SAMOCHOD";
            columnExpression72.ColumnName = "ID_IHP_SAMOCHOD";
            table5.Name = "IHP_SAMOCHOD";
            columnExpression72.Table = table5;
            column72.Expression = columnExpression72;
            column73.Alias = "IHP_SAMOCHOD_NAZWA";
            columnExpression73.ColumnName = "NAZWA";
            columnExpression73.Table = table5;
            column73.Expression = columnExpression73;
            columnExpression74.ColumnName = "NRREJ";
            columnExpression74.Table = table5;
            column74.Expression = columnExpression74;
            column75.Alias = "IHP_SAMOCHOD_ID_IHP_KIEROWCA";
            columnExpression75.ColumnName = "ID_IHP_KIEROWCA";
            columnExpression75.Table = table5;
            column75.Expression = columnExpression75;
            columnExpression76.ColumnName = "TARA";
            columnExpression76.Table = table5;
            column76.Expression = columnExpression76;
            column77.Alias = "IHP_KIEROWCA_ID_IHP_KIEROWCA";
            columnExpression77.ColumnName = "ID_IHP_KIEROWCA";
            table6.Name = "IHP_KIEROWCA";
            columnExpression77.Table = table6;
            column77.Expression = columnExpression77;
            column78.Alias = "IHP_KIEROWCA_NAZWA";
            columnExpression78.ColumnName = "NAZWA";
            columnExpression78.Table = table6;
            column78.Expression = columnExpression78;
            column79.Alias = "IHP_KIEROWCA_TELEFON";
            columnExpression79.ColumnName = "TELEFON";
            columnExpression79.Table = table6;
            column79.Expression = columnExpression79;
            column80.Alias = "IHP_KIEROWCA_ID_IHP_KONTRAHENT";
            columnExpression80.ColumnName = "ID_IHP_KONTRAHENT";
            columnExpression80.Table = table6;
            column80.Expression = columnExpression80;
            column81.Alias = "IHP_KARTOTEKA_ID_IHP_KARTOTEKA";
            columnExpression81.ColumnName = "ID_IHP_KARTOTEKA";
            table7.Name = "IHP_KARTOTEKA";
            columnExpression81.Table = table7;
            column81.Expression = columnExpression81;
            columnExpression82.ColumnName = "ID_IHP_STAWKAVAT";
            columnExpression82.Table = table7;
            column82.Expression = columnExpression82;
            columnExpression83.ColumnName = "ID_IHP_RODZAJKART";
            columnExpression83.Table = table7;
            column83.Expression = columnExpression83;
            columnExpression84.ColumnName = "ID_IHP_JM";
            columnExpression84.Table = table7;
            column84.Expression = columnExpression84;
            columnExpression85.ColumnName = "INDEKS";
            columnExpression85.Table = table7;
            column85.Expression = columnExpression85;
            columnExpression86.ColumnName = "NAZWASKR";
            columnExpression86.Table = table7;
            column86.Expression = columnExpression86;
            columnExpression87.ColumnName = "NAZWADL";
            columnExpression87.Table = table7;
            column87.Expression = columnExpression87;
            columnExpression88.ColumnName = "SWW";
            columnExpression88.Table = table7;
            column88.Expression = columnExpression88;
            columnExpression89.ColumnName = "PKWIU";
            columnExpression89.Table = table7;
            column89.Expression = columnExpression89;
            columnExpression90.ColumnName = "UWAGI";
            columnExpression90.Table = table7;
            column90.Expression = columnExpression90;
            columnExpression91.ColumnName = "KODEAN";
            columnExpression91.Table = table7;
            column91.Expression = columnExpression91;
            columnExpression92.ColumnName = "ID_IHP_GRUPAKART";
            columnExpression92.Table = table7;
            column92.Expression = columnExpression92;
            columnExpression93.ColumnName = "ID_TOWSUBJECT";
            columnExpression93.Table = table7;
            column93.Expression = columnExpression93;
            selectQuery3.Columns.Add(column39);
            selectQuery3.Columns.Add(column40);
            selectQuery3.Columns.Add(column41);
            selectQuery3.Columns.Add(column42);
            selectQuery3.Columns.Add(column43);
            selectQuery3.Columns.Add(column44);
            selectQuery3.Columns.Add(column45);
            selectQuery3.Columns.Add(column46);
            selectQuery3.Columns.Add(column47);
            selectQuery3.Columns.Add(column48);
            selectQuery3.Columns.Add(column49);
            selectQuery3.Columns.Add(column50);
            selectQuery3.Columns.Add(column51);
            selectQuery3.Columns.Add(column52);
            selectQuery3.Columns.Add(column53);
            selectQuery3.Columns.Add(column54);
            selectQuery3.Columns.Add(column55);
            selectQuery3.Columns.Add(column56);
            selectQuery3.Columns.Add(column57);
            selectQuery3.Columns.Add(column58);
            selectQuery3.Columns.Add(column59);
            selectQuery3.Columns.Add(column60);
            selectQuery3.Columns.Add(column61);
            selectQuery3.Columns.Add(column62);
            selectQuery3.Columns.Add(column63);
            selectQuery3.Columns.Add(column64);
            selectQuery3.Columns.Add(column65);
            selectQuery3.Columns.Add(column66);
            selectQuery3.Columns.Add(column67);
            selectQuery3.Columns.Add(column68);
            selectQuery3.Columns.Add(column69);
            selectQuery3.Columns.Add(column70);
            selectQuery3.Columns.Add(column71);
            selectQuery3.Columns.Add(column72);
            selectQuery3.Columns.Add(column73);
            selectQuery3.Columns.Add(column74);
            selectQuery3.Columns.Add(column75);
            selectQuery3.Columns.Add(column76);
            selectQuery3.Columns.Add(column77);
            selectQuery3.Columns.Add(column78);
            selectQuery3.Columns.Add(column79);
            selectQuery3.Columns.Add(column80);
            selectQuery3.Columns.Add(column81);
            selectQuery3.Columns.Add(column82);
            selectQuery3.Columns.Add(column83);
            selectQuery3.Columns.Add(column84);
            selectQuery3.Columns.Add(column85);
            selectQuery3.Columns.Add(column86);
            selectQuery3.Columns.Add(column87);
            selectQuery3.Columns.Add(column88);
            selectQuery3.Columns.Add(column89);
            selectQuery3.Columns.Add(column90);
            selectQuery3.Columns.Add(column91);
            selectQuery3.Columns.Add(column92);
            selectQuery3.Columns.Add(column93);
            selectQuery3.MetaSerializable = "<Meta X=\"430\" Y=\"30\" Width=\"240\" Height=\"972\" />";
            selectQuery3.Name = "IHP_WAZENIE";
            relationColumnInfo1.NestedKeyColumn = "ID_IHP_KONTRAHENT_ARCH";
            relationColumnInfo1.ParentKeyColumn = "ID_IHP_KONTRAHENT_ARCH";
            join1.KeyColumns.Add(relationColumnInfo1);
            join1.Nested = table4;
            join1.Parent = table3;
            relationColumnInfo2.NestedKeyColumn = "ID_IHP_SAMOCHOD";
            relationColumnInfo2.ParentKeyColumn = "ID_IHP_SAMOCHOD";
            join2.KeyColumns.Add(relationColumnInfo2);
            join2.Nested = table5;
            join2.Parent = table3;
            relationColumnInfo3.NestedKeyColumn = "ID_IHP_KIEROWCA";
            relationColumnInfo3.ParentKeyColumn = "ID_IHP_KIEROWCA";
            join3.KeyColumns.Add(relationColumnInfo3);
            join3.Nested = table6;
            join3.Parent = table3;
            relationColumnInfo4.NestedKeyColumn = "ID_IHP_KARTOTEKA";
            relationColumnInfo4.ParentKeyColumn = "ID_IHP_KARTOTEKA";
            join4.KeyColumns.Add(relationColumnInfo4);
            join4.Nested = table7;
            join4.Parent = table3;
            selectQuery3.Relations.Add(join1);
            selectQuery3.Relations.Add(join2);
            selectQuery3.Relations.Add(join3);
            selectQuery3.Relations.Add(join4);
            selectQuery3.Tables.Add(table3);
            selectQuery3.Tables.Add(table4);
            selectQuery3.Tables.Add(table5);
            selectQuery3.Tables.Add(table6);
            selectQuery3.Tables.Add(table7);
            columnExpression94.ColumnName = "ID_IHP_KIEROWCA";
            table8.Name = "IHP_KIEROWCA";
            columnExpression94.Table = table8;
            column94.Expression = columnExpression94;
            columnExpression95.ColumnName = "NAZWA";
            columnExpression95.Table = table8;
            column95.Expression = columnExpression95;
            columnExpression96.ColumnName = "TELEFON";
            columnExpression96.Table = table8;
            column96.Expression = columnExpression96;
            columnExpression97.ColumnName = "ID_IHP_KONTRAHENT";
            columnExpression97.Table = table8;
            column97.Expression = columnExpression97;
            selectQuery4.Columns.Add(column94);
            selectQuery4.Columns.Add(column95);
            selectQuery4.Columns.Add(column96);
            selectQuery4.Columns.Add(column97);
            selectQuery4.MetaSerializable = "<Meta X=\"760\" Y=\"50\" Width=\"190\" Height=\"105\" />";
            selectQuery4.Name = "IHP_KIEROWCA";
            selectQuery4.Tables.Add(table8);
            columnExpression98.ColumnName = "ID_IHP_KARTOTEKA";
            table9.Name = "IHP_KARTOTEKA";
            columnExpression98.Table = table9;
            column98.Expression = columnExpression98;
            columnExpression99.ColumnName = "ID_IHP_STAWKAVAT";
            columnExpression99.Table = table9;
            column99.Expression = columnExpression99;
            columnExpression100.ColumnName = "ID_IHP_RODZAJKART";
            columnExpression100.Table = table9;
            column100.Expression = columnExpression100;
            columnExpression101.ColumnName = "ID_IHP_JM";
            columnExpression101.Table = table9;
            column101.Expression = columnExpression101;
            columnExpression102.ColumnName = "INDEKS";
            columnExpression102.Table = table9;
            column102.Expression = columnExpression102;
            columnExpression103.ColumnName = "NAZWASKR";
            columnExpression103.Table = table9;
            column103.Expression = columnExpression103;
            columnExpression104.ColumnName = "NAZWADL";
            columnExpression104.Table = table9;
            column104.Expression = columnExpression104;
            columnExpression105.ColumnName = "SWW";
            columnExpression105.Table = table9;
            column105.Expression = columnExpression105;
            columnExpression106.ColumnName = "PKWIU";
            columnExpression106.Table = table9;
            column106.Expression = columnExpression106;
            columnExpression107.ColumnName = "UWAGI";
            columnExpression107.Table = table9;
            column107.Expression = columnExpression107;
            columnExpression108.ColumnName = "KODEAN";
            columnExpression108.Table = table9;
            column108.Expression = columnExpression108;
            columnExpression109.ColumnName = "ID_IHP_GRUPAKART";
            columnExpression109.Table = table9;
            column109.Expression = columnExpression109;
            columnExpression110.ColumnName = "ID_TOWSUBJECT";
            columnExpression110.Table = table9;
            column110.Expression = columnExpression110;
            selectQuery5.Columns.Add(column98);
            selectQuery5.Columns.Add(column99);
            selectQuery5.Columns.Add(column100);
            selectQuery5.Columns.Add(column101);
            selectQuery5.Columns.Add(column102);
            selectQuery5.Columns.Add(column103);
            selectQuery5.Columns.Add(column104);
            selectQuery5.Columns.Add(column105);
            selectQuery5.Columns.Add(column106);
            selectQuery5.Columns.Add(column107);
            selectQuery5.Columns.Add(column108);
            selectQuery5.Columns.Add(column109);
            selectQuery5.Columns.Add(column110);
            selectQuery5.MetaSerializable = "<Meta X=\"860\" Y=\"320\" Width=\"190\" Height=\"258\" />";
            selectQuery5.Name = "IHP_KARTOTEKA";
            selectQuery5.Tables.Add(table9);
            columnExpression111.ColumnName = "ID_IHP_RODZAJDOK";
            table10.Name = "IHP_RODZAJDOK";
            columnExpression111.Table = table10;
            column111.Expression = columnExpression111;
            columnExpression112.ColumnName = "OPIS";
            columnExpression112.Table = table10;
            column112.Expression = columnExpression112;
            columnExpression113.ColumnName = "KIERUNEKMAG";
            columnExpression113.Table = table10;
            column113.Expression = columnExpression113;
            selectQuery6.Columns.Add(column111);
            selectQuery6.Columns.Add(column112);
            selectQuery6.Columns.Add(column113);
            selectQuery6.MetaSerializable = "<Meta X=\"1300\" Y=\"540\" Width=\"100\" Height=\"88\" />";
            selectQuery6.Name = "IHP_RODZAJDOK";
            selectQuery6.Tables.Add(table10);
            columnExpression114.ColumnName = "ID_IHP_SAMOCHOD";
            table11.Name = "IHP_SAMOCHOD";
            columnExpression114.Table = table11;
            column114.Expression = columnExpression114;
            columnExpression115.ColumnName = "NAZWA";
            columnExpression115.Table = table11;
            column115.Expression = columnExpression115;
            columnExpression116.ColumnName = "NRREJ";
            columnExpression116.Table = table11;
            column116.Expression = columnExpression116;
            columnExpression117.ColumnName = "ID_IHP_KIEROWCA";
            columnExpression117.Table = table11;
            column117.Expression = columnExpression117;
            columnExpression118.ColumnName = "TARA";
            columnExpression118.Table = table11;
            column118.Expression = columnExpression118;
            selectQuery7.Columns.Add(column114);
            selectQuery7.Columns.Add(column115);
            selectQuery7.Columns.Add(column116);
            selectQuery7.Columns.Add(column117);
            selectQuery7.Columns.Add(column118);
            selectQuery7.MetaSerializable = "<Meta X=\"1130\" Y=\"110\" Width=\"210\" Height=\"122\" />";
            selectQuery7.Name = "IHP_SAMOCHOD";
            selectQuery7.Tables.Add(table11);
            columnExpression119.ColumnName = "ID_IHP_WAZENIE";
            table12.Name = "IHP_WAZENIE";
            columnExpression119.Table = table12;
            column119.Expression = columnExpression119;
            columnExpression120.ColumnName = "DATAWJAZD";
            columnExpression120.Table = table12;
            column120.Expression = columnExpression120;
            columnExpression121.ColumnName = "DATAWYJAZD";
            columnExpression121.Table = table12;
            column121.Expression = columnExpression121;
            columnExpression122.ColumnName = "ID_IHP_KIEROWCA";
            columnExpression122.Table = table12;
            column122.Expression = columnExpression122;
            columnExpression123.ColumnName = "ID_IHP_SAMOCHOD";
            columnExpression123.Table = table12;
            column123.Expression = columnExpression123;
            columnExpression124.ColumnName = "WAGAWJAZD";
            columnExpression124.Table = table12;
            column124.Expression = columnExpression124;
            columnExpression125.ColumnName = "WAGAWYJAZD";
            columnExpression125.Table = table12;
            column125.Expression = columnExpression125;
            columnExpression126.ColumnName = "ID_IHP_KONTRAHENT_ARCH";
            columnExpression126.Table = table12;
            column126.Expression = columnExpression126;
            columnExpression127.ColumnName = "ID_IHP_KARTOTEKA";
            columnExpression127.Table = table12;
            column127.Expression = columnExpression127;
            columnExpression128.ColumnName = "ID_IHP_RODZAJDOK";
            columnExpression128.Table = table12;
            column128.Expression = columnExpression128;
            columnExpression129.ColumnName = "STATUS";
            columnExpression129.Table = table12;
            column129.Expression = columnExpression129;
            columnExpression130.ColumnName = "NRKWIT";
            columnExpression130.Table = table12;
            column130.Expression = columnExpression130;
            columnExpression131.ColumnName = "NRKWITWEW";
            columnExpression131.Table = table12;
            column131.Expression = columnExpression131;
            column132.Alias = "IHP_KIEROWCA_ID_IHP_KIEROWCA";
            columnExpression132.ColumnName = "ID_IHP_KIEROWCA";
            table13.Name = "IHP_KIEROWCA";
            columnExpression132.Table = table13;
            column132.Expression = columnExpression132;
            columnExpression133.ColumnName = "NAZWA";
            columnExpression133.Table = table13;
            column133.Expression = columnExpression133;
            columnExpression134.ColumnName = "TELEFON";
            columnExpression134.Table = table13;
            column134.Expression = columnExpression134;
            columnExpression135.ColumnName = "ID_IHP_KONTRAHENT";
            columnExpression135.Table = table13;
            column135.Expression = columnExpression135;
            column136.Alias = "IHP_KONTRAHENT_ARCH_ID_IHP_KONTRAHENT_ARCH";
            columnExpression136.ColumnName = "ID_IHP_KONTRAHENT_ARCH";
            table14.Name = "IHP_KONTRAHENT_ARCH";
            columnExpression136.Table = table14;
            column136.Expression = columnExpression136;
            column137.Alias = "IHP_KONTRAHENT_ARCH_ID_IHP_KONTRAHENT";
            columnExpression137.ColumnName = "ID_IHP_KONTRAHENT";
            columnExpression137.Table = table14;
            column137.Expression = columnExpression137;
            columnExpression138.ColumnName = "NRKONTRAH";
            columnExpression138.Table = table14;
            column138.Expression = columnExpression138;
            columnExpression139.ColumnName = "NIP";
            columnExpression139.Table = table14;
            column139.Expression = columnExpression139;
            column140.Alias = "IHP_KONTRAHENT_ARCH_NAZWA";
            columnExpression140.ColumnName = "NAZWA";
            columnExpression140.Table = table14;
            column140.Expression = columnExpression140;
            columnExpression141.ColumnName = "MIEJSCOWOSC";
            columnExpression141.Table = table14;
            column141.Expression = columnExpression141;
            columnExpression142.ColumnName = "KODPOCZTOWY";
            columnExpression142.Table = table14;
            column142.Expression = columnExpression142;
            columnExpression143.ColumnName = "POCZTA";
            columnExpression143.Table = table14;
            column143.Expression = columnExpression143;
            columnExpression144.ColumnName = "ULICA";
            columnExpression144.Table = table14;
            column144.Expression = columnExpression144;
            columnExpression145.ColumnName = "NRDOMU";
            columnExpression145.Table = table14;
            column145.Expression = columnExpression145;
            columnExpression146.ColumnName = "NRLOKALU";
            columnExpression146.Table = table14;
            column146.Expression = columnExpression146;
            columnExpression147.ColumnName = "EMAIL";
            columnExpression147.Table = table14;
            column147.Expression = columnExpression147;
            column148.Alias = "IHP_KONTRAHENT_ARCH_TELEFON";
            columnExpression148.ColumnName = "TELEFON";
            columnExpression148.Table = table14;
            column148.Expression = columnExpression148;
            columnExpression149.ColumnName = "AKTYWNY";
            columnExpression149.Table = table14;
            column149.Expression = columnExpression149;
            columnExpression150.ColumnName = "ID_IHP_DEFCENY";
            columnExpression150.Table = table14;
            column150.Expression = columnExpression150;
            columnExpression151.ColumnName = "ID_KH_SUBJECT";
            columnExpression151.Table = table14;
            column151.Expression = columnExpression151;
            columnExpression152.ColumnName = "TELKOM";
            columnExpression152.Table = table14;
            column152.Expression = columnExpression152;
            columnExpression153.ColumnName = "TYPKONTRAH";
            columnExpression153.Table = table14;
            column153.Expression = columnExpression153;
            columnExpression154.ColumnName = "NAZWAPELNA";
            columnExpression154.Table = table14;
            column154.Expression = columnExpression154;
            columnExpression155.ColumnName = "ID_IHP_RODZAJDOKDEF";
            columnExpression155.Table = table14;
            column155.Expression = columnExpression155;
            column156.Alias = "IHP_KARTOTEKA_ID_IHP_KARTOTEKA";
            columnExpression156.ColumnName = "ID_IHP_KARTOTEKA";
            table15.Name = "IHP_KARTOTEKA";
            columnExpression156.Table = table15;
            column156.Expression = columnExpression156;
            columnExpression157.ColumnName = "ID_IHP_STAWKAVAT";
            columnExpression157.Table = table15;
            column157.Expression = columnExpression157;
            columnExpression158.ColumnName = "ID_IHP_RODZAJKART";
            columnExpression158.Table = table15;
            column158.Expression = columnExpression158;
            columnExpression159.ColumnName = "ID_IHP_JM";
            columnExpression159.Table = table15;
            column159.Expression = columnExpression159;
            columnExpression160.ColumnName = "INDEKS";
            columnExpression160.Table = table15;
            column160.Expression = columnExpression160;
            columnExpression161.ColumnName = "NAZWASKR";
            columnExpression161.Table = table15;
            column161.Expression = columnExpression161;
            columnExpression162.ColumnName = "NAZWADL";
            columnExpression162.Table = table15;
            column162.Expression = columnExpression162;
            columnExpression163.ColumnName = "SWW";
            columnExpression163.Table = table15;
            column163.Expression = columnExpression163;
            columnExpression164.ColumnName = "PKWIU";
            columnExpression164.Table = table15;
            column164.Expression = columnExpression164;
            columnExpression165.ColumnName = "UWAGI";
            columnExpression165.Table = table15;
            column165.Expression = columnExpression165;
            columnExpression166.ColumnName = "KODEAN";
            columnExpression166.Table = table15;
            column166.Expression = columnExpression166;
            columnExpression167.ColumnName = "ID_IHP_GRUPAKART";
            columnExpression167.Table = table15;
            column167.Expression = columnExpression167;
            columnExpression168.ColumnName = "ID_TOWSUBJECT";
            columnExpression168.Table = table15;
            column168.Expression = columnExpression168;
            selectQuery8.Columns.Add(column119);
            selectQuery8.Columns.Add(column120);
            selectQuery8.Columns.Add(column121);
            selectQuery8.Columns.Add(column122);
            selectQuery8.Columns.Add(column123);
            selectQuery8.Columns.Add(column124);
            selectQuery8.Columns.Add(column125);
            selectQuery8.Columns.Add(column126);
            selectQuery8.Columns.Add(column127);
            selectQuery8.Columns.Add(column128);
            selectQuery8.Columns.Add(column129);
            selectQuery8.Columns.Add(column130);
            selectQuery8.Columns.Add(column131);
            selectQuery8.Columns.Add(column132);
            selectQuery8.Columns.Add(column133);
            selectQuery8.Columns.Add(column134);
            selectQuery8.Columns.Add(column135);
            selectQuery8.Columns.Add(column136);
            selectQuery8.Columns.Add(column137);
            selectQuery8.Columns.Add(column138);
            selectQuery8.Columns.Add(column139);
            selectQuery8.Columns.Add(column140);
            selectQuery8.Columns.Add(column141);
            selectQuery8.Columns.Add(column142);
            selectQuery8.Columns.Add(column143);
            selectQuery8.Columns.Add(column144);
            selectQuery8.Columns.Add(column145);
            selectQuery8.Columns.Add(column146);
            selectQuery8.Columns.Add(column147);
            selectQuery8.Columns.Add(column148);
            selectQuery8.Columns.Add(column149);
            selectQuery8.Columns.Add(column150);
            selectQuery8.Columns.Add(column151);
            selectQuery8.Columns.Add(column152);
            selectQuery8.Columns.Add(column153);
            selectQuery8.Columns.Add(column154);
            selectQuery8.Columns.Add(column155);
            selectQuery8.Columns.Add(column156);
            selectQuery8.Columns.Add(column157);
            selectQuery8.Columns.Add(column158);
            selectQuery8.Columns.Add(column159);
            selectQuery8.Columns.Add(column160);
            selectQuery8.Columns.Add(column161);
            selectQuery8.Columns.Add(column162);
            selectQuery8.Columns.Add(column163);
            selectQuery8.Columns.Add(column164);
            selectQuery8.Columns.Add(column165);
            selectQuery8.Columns.Add(column166);
            selectQuery8.Columns.Add(column167);
            selectQuery8.Columns.Add(column168);
            selectQuery8.Name = "IHP_WAZENIE_1";
            queryParameter1.Name = "WAZENIEID";
            queryParameter1.Type = typeof(int);
            queryParameter1.ValueInfo = "0";
            selectQuery8.Parameters.Add(queryParameter1);
            relationColumnInfo5.NestedKeyColumn = "ID_IHP_KIEROWCA";
            relationColumnInfo5.ParentKeyColumn = "ID_IHP_KIEROWCA";
            join5.KeyColumns.Add(relationColumnInfo5);
            join5.Nested = table13;
            join5.Parent = table12;
            relationColumnInfo6.NestedKeyColumn = "ID_IHP_KONTRAHENT_ARCH";
            relationColumnInfo6.ParentKeyColumn = "ID_IHP_KONTRAHENT_ARCH";
            join6.KeyColumns.Add(relationColumnInfo6);
            join6.Nested = table14;
            join6.Parent = table12;
            relationColumnInfo7.NestedKeyColumn = "ID_IHP_KARTOTEKA";
            relationColumnInfo7.ParentKeyColumn = "ID_IHP_KARTOTEKA";
            join7.KeyColumns.Add(relationColumnInfo7);
            join7.Nested = table15;
            join7.Parent = table12;
            selectQuery8.Relations.Add(join5);
            selectQuery8.Relations.Add(join6);
            selectQuery8.Relations.Add(join7);
            selectQuery8.Tables.Add(table12);
            selectQuery8.Tables.Add(table13);
            selectQuery8.Tables.Add(table14);
            selectQuery8.Tables.Add(table15);
            this.sqlDataSource1.Queries.AddRange(new DevExpress.DataAccess.Sql.SqlQuery[] {
            selectQuery1,
            selectQuery2,
            selectQuery3,
            selectQuery4,
            selectQuery5,
            selectQuery6,
            selectQuery7,
            selectQuery8});
            masterDetailInfo1.DetailQueryName = "IHP_KONTRAHENT";
            relationColumnInfo8.NestedKeyColumn = "ID_IHP_KONTRAHENT";
            relationColumnInfo8.ParentKeyColumn = "ID_IHP_KONTRAHENT";
            masterDetailInfo1.KeyColumns.Add(relationColumnInfo8);
            masterDetailInfo1.MasterQueryName = "IHP_KONTRAHENT";
            masterDetailInfo2.DetailQueryName = "IHP_KONTRAHENT_ARCH";
            relationColumnInfo9.NestedKeyColumn = "ID_IHP_KONTRAHENT_ARCH";
            relationColumnInfo9.ParentKeyColumn = "ID_IHP_KONTRAHENT_ARCH";
            masterDetailInfo2.KeyColumns.Add(relationColumnInfo9);
            masterDetailInfo2.MasterQueryName = "IHP_WAZENIE";
            masterDetailInfo3.DetailQueryName = "IHP_KARTOTEKA";
            relationColumnInfo10.NestedKeyColumn = "ID_IHP_KARTOTEKA";
            relationColumnInfo10.ParentKeyColumn = "ID_IHP_KARTOTEKA";
            masterDetailInfo3.KeyColumns.Add(relationColumnInfo10);
            masterDetailInfo3.MasterQueryName = "IHP_WAZENIE";
            masterDetailInfo4.DetailQueryName = "IHP_KIEROWCA";
            relationColumnInfo11.NestedKeyColumn = "ID_IHP_KIEROWCA";
            relationColumnInfo11.ParentKeyColumn = "ID_IHP_KIEROWCA";
            masterDetailInfo4.KeyColumns.Add(relationColumnInfo11);
            masterDetailInfo4.MasterQueryName = "IHP_WAZENIE";
            masterDetailInfo5.DetailQueryName = "IHP_SAMOCHOD";
            relationColumnInfo12.NestedKeyColumn = "ID_IHP_SAMOCHOD";
            relationColumnInfo12.ParentKeyColumn = "ID_IHP_SAMOCHOD";
            masterDetailInfo5.KeyColumns.Add(relationColumnInfo12);
            masterDetailInfo5.MasterQueryName = "IHP_WAZENIE";
            this.sqlDataSource1.Relations.AddRange(new DevExpress.DataAccess.Sql.MasterDetailInfo[] {
            masterDetailInfo1,
            masterDetailInfo2,
            masterDetailInfo3,
            masterDetailInfo4,
            masterDetailInfo5});
            this.sqlDataSource1.ResultSchemaSerializable = resources.GetString("sqlDataSource1.ResultSchemaSerializable");
            // 
            // DetailReport
            // 
            this.DetailReport.Bands.AddRange(new DevExpress.XtraReports.UI.Band[] {
            this.Detail1});
            this.DetailReport.Level = 0;
            this.DetailReport.Name = "DetailReport";
            // 
            // Detail1
            // 
            this.Detail1.Controls.AddRange(new DevExpress.XtraReports.UI.XRControl[] {
            this.xrLabel4,
            this.xrLabel3,
            this.xrLabel2,
            this.xrLabel1});
            this.Detail1.HeightF = 100F;
            this.Detail1.Name = "Detail1";
            // 
            // xrLabel1
            // 
            this.xrLabel1.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "IHP_WAZENIE.INDEKS")});
            this.xrLabel1.LocationFloat = new DevExpress.Utils.PointFloat(10.00001F, 0F);
            this.xrLabel1.Name = "xrLabel1";
            this.xrLabel1.Padding = new DevExpress.XtraPrinting.PaddingInfo(2, 2, 0, 0, 100F);
            this.xrLabel1.SizeF = new System.Drawing.SizeF(100F, 23F);
            this.xrLabel1.Text = "xrLabel1";
            // 
            // xrLabel2
            // 
            this.xrLabel2.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "IHP_WAZENIE.WAGAWJAZD")});
            this.xrLabel2.LocationFloat = new DevExpress.Utils.PointFloat(140.625F, 0F);
            this.xrLabel2.Name = "xrLabel2";
            this.xrLabel2.Padding = new DevExpress.XtraPrinting.PaddingInfo(2, 2, 0, 0, 96F);
            this.xrLabel2.SizeF = new System.Drawing.SizeF(100F, 23F);
            this.xrLabel2.Text = "xrLabel2";
            // 
            // xrLabel3
            // 
            this.xrLabel3.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "IHP_WAZENIE.WAGAWYJAZD")});
            this.xrLabel3.LocationFloat = new DevExpress.Utils.PointFloat(273.9583F, 0F);
            this.xrLabel3.Name = "xrLabel3";
            this.xrLabel3.Padding = new DevExpress.XtraPrinting.PaddingInfo(2, 2, 0, 0, 96F);
            this.xrLabel3.SizeF = new System.Drawing.SizeF(100F, 23F);
            this.xrLabel3.Text = "xrLabel3";
            // 
            // xrLabel4
            // 
            this.xrLabel4.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "IHP_WAZENIE.IHP_WAZENIEIHP_KARTOTEKA.INDEKS")});
            this.xrLabel4.LocationFloat = new DevExpress.Utils.PointFloat(398.9583F, 0F);
            this.xrLabel4.Name = "xrLabel4";
            this.xrLabel4.Padding = new DevExpress.XtraPrinting.PaddingInfo(2, 2, 0, 0, 96F);
            this.xrLabel4.SizeF = new System.Drawing.SizeF(100F, 23F);
            this.xrLabel4.Text = "xrLabel4";
            // 
            // xrLabel5
            // 
            this.xrLabel5.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "IHP_WAZENIE.IHP_WAZENIEIHP_KONTRAHENT_ARCH.NAZWA")});
            this.xrLabel5.LocationFloat = new DevExpress.Utils.PointFloat(10.00001F, 0F);
            this.xrLabel5.Name = "xrLabel5";
            this.xrLabel5.Padding = new DevExpress.XtraPrinting.PaddingInfo(2, 2, 0, 0, 96F);
            this.xrLabel5.SizeF = new System.Drawing.SizeF(230.625F, 23F);
            this.xrLabel5.Text = "xrLabel5";
            // 
            // xrLabel6
            // 
            this.xrLabel6.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "IHP_WAZENIE.IHP_WAZENIEIHP_KONTRAHENT_ARCH.KODPOCZTOWY")});
            this.xrLabel6.LocationFloat = new DevExpress.Utils.PointFloat(10.00001F, 22.99999F);
            this.xrLabel6.Name = "xrLabel6";
            this.xrLabel6.Padding = new DevExpress.XtraPrinting.PaddingInfo(2, 2, 0, 0, 96F);
            this.xrLabel6.SizeF = new System.Drawing.SizeF(100F, 23F);
            this.xrLabel6.Text = "xrLabel6";
            // 
            // xrLabel7
            // 
            this.xrLabel7.DataBindings.AddRange(new DevExpress.XtraReports.UI.XRBinding[] {
            new DevExpress.XtraReports.UI.XRBinding("Text", null, "IHP_WAZENIE.IHP_WAZENIEIHP_KONTRAHENT_ARCH.MIEJSCOWOSC")});
            this.xrLabel7.LocationFloat = new DevExpress.Utils.PointFloat(140.625F, 22.99999F);
            this.xrLabel7.Name = "xrLabel7";
            this.xrLabel7.Padding = new DevExpress.XtraPrinting.PaddingInfo(2, 2, 0, 0, 96F);
            this.xrLabel7.SizeF = new System.Drawing.SizeF(112.5F, 23F);
            this.xrLabel7.Text = "xrLabel7";
            // 
            // rptKwitDB
            // 
            this.Bands.AddRange(new DevExpress.XtraReports.UI.Band[] {
            this.Detail,
            this.TopMargin,
            this.BottomMargin,
            this.DetailReport});
            this.ComponentStorage.AddRange(new System.ComponentModel.IComponent[] {
            this.sqlDataSource1});
            this.DataMember = "IHP_WAZENIE";
            this.DataSource = this.sqlDataSource1;
            this.FilterString = "[ID_IHP_WAZENIE] = ?";
            this.Margins = new System.Drawing.Printing.Margins(100, 100, 0, 100);
            this.Version = "17.1";
            ((System.ComponentModel.ISupportInitialize)(this)).EndInit();

        }

        #endregion

        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
        private DevExpress.DataAccess.Sql.SqlDataSource sqlDataSource1;
        private DevExpress.XtraReports.UI.DetailReportBand DetailReport;
        private DevExpress.XtraReports.UI.DetailBand Detail1;
        private DevExpress.XtraReports.UI.XRLabel xrLabel4;
        private DevExpress.XtraReports.UI.XRLabel xrLabel3;
        private DevExpress.XtraReports.UI.XRLabel xrLabel2;
        private DevExpress.XtraReports.UI.XRLabel xrLabel1;
        private DevExpress.XtraReports.UI.XRLabel xrLabel7;
        private DevExpress.XtraReports.UI.XRLabel xrLabel6;
        private DevExpress.XtraReports.UI.XRLabel xrLabel5;
    }
}
