//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lustra
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    public partial class CECHAKART: INotifyPropertyChanged
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CECHAKART()
        {
            this.WYSTCECHKART = new HashSet<WYSTCECHKART>();
        }
    
        public int ID_CECHAKART { get; set; }
        private string _nazwa;
        public string NAZWA {
            get
            {
                return _nazwa;
            }
             set
            {
                _nazwa = value;
                RisePropertyChanged("NAZWA");


            }
                
                }

        protected void RisePropertyChanged(string name)
        {
            if (PropertyChanged != null)
            {
                PropertyChanged(this, new PropertyChangedEventArgs(name));
            }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WYSTCECHKART> WYSTCECHKART { get; set; }

        public event PropertyChangedEventHandler PropertyChanged;
    }
}
