//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KpInfohelp
{
    using System;
    using System.Collections.Generic;
    
    public partial class IHP_WYST_JZ
    {
        public int ID_IHP_WYST_JZ { get; set; }
        public int ID_IHP_JZ { get; set; }
        public Nullable<int> ID_KARTOTEKA { get; set; }
        public short AKTYWNA { get; set; }
    
        public virtual IHP_JZ IHP_JZ { get; set; }
    }
}
