//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KpInfohelp
{
    using System;
    using System.Collections.Generic;
    
    public partial class IHP_GRUPAKART
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IHP_GRUPAKART()
        {
            this.IHP_WYSTGRKART = new HashSet<IHP_WYSTGRKART>();
        }
    
        public int ID_IHP_GRUPAKART { get; set; }
        public string NAZWAGRUPY { get; set; }
        public string KODGRUPY { get; set; }
        public string KODZLOZONY { get; set; }
        public string NAZWAZLOZONA { get; set; }
        public int ID_IHP_RODZGRUPKART { get; set; }
        public int ID_IHP_GRUPAKART_NADRZ { get; set; }
    
        public virtual IHP_RODZGRUPKART IHP_RODZGRUPKART { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IHP_WYSTGRKART> IHP_WYSTGRKART { get; set; }
    }
}
