//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KpInfohelp
{
    using System;
    using System.Collections.Generic;
    
    public partial class IHP_WYSTCECHKART
    {
        public int ID_WYSTCECHKART { get; set; }
        public int ID_KARTOTEKA { get; set; }
        public int ID_CECHAKART { get; set; }
        public string WARTOSC { get; set; }
    }
}
