//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KpInfohelp
{
    using System;
    using System.Collections.Generic;
    
    public partial class IHP_COMCONFIG
    {
        public int ID { get; set; }
        public string VAL { get; set; }
        public Nullable<int> TYP { get; set; }
    }
}
