//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KpInfohelp
{
    using System;
    using System.Collections.Generic;
    
    public partial class IHP_DOSTAWA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IHP_DOSTAWA()
        {
            this.IHP_ROZCHDOST = new HashSet<IHP_ROZCHDOST>();
        }
    
        public int ID_IHP_DOSTAWA { get; set; }
        public Nullable<decimal> ILOSC { get; set; }
        public Nullable<decimal> ILOSCAKT { get; set; }
        public Nullable<short> ZREALIZOWANA { get; set; }
        public Nullable<System.DateTime> DATADOSTAWY { get; set; }
        public Nullable<int> ID_IHP_POZDOK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IHP_ROZCHDOST> IHP_ROZCHDOST { get; set; }
    }
}
