//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KpInfohelp
{
    using System;
    using System.Collections.Generic;
    
    public partial class IHP_MODEL
    {
        public int ID_IHP_MODEL { get; set; }
        public int ID_IHP_PRODUCENT { get; set; }
        public string NAME { get; set; }
    
        public virtual IHP_PRODUCENT IHP_PRODUCENT { get; set; }
    }
}
