//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KpInfohelp
{
    using System;
    using System.Collections.Generic;
    
    public partial class IHP_CENNIKHISTORIA
    {
        public int ID_IHP_CENNIKHISTORIA { get; set; }
        public int ID_IHP_CENNIK { get; set; }
        public System.DateTime DATAWPISU { get; set; }
        public decimal CENAZ { get; set; }
        public decimal CENANA { get; set; }
        public int ID_IHP_ZAM_USERS { get; set; }
    
        public virtual IHP_CENNIK IHP_CENNIK { get; set; }
        public virtual IHP_ZAM_USERS IHP_ZAM_USERS { get; set; }
    }
}
