//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KpInfohelp
{
    using System;
    using System.Collections.Generic;
    
    public partial class IHP_NUMERACJA
    {
        public int ID_IHP_NUMERACJA { get; set; }
        public int ID_TABELA { get; set; }
        public int NUMER { get; set; }
        public string NAZWA { get; set; }
    }
}
