//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KpInfohelp
{
    using System;
    using System.Collections.Generic;
    
    public partial class IHP_SAMOCHOD
    {
        public int ID_IHP_SAMOCHOD { get; set; }
        public string NAZWA { get; set; }
        public string NRREJ { get; set; }
        public Nullable<int> ID_IHP_KIEROWCA { get; set; }
        public Nullable<decimal> TARA { get; set; }
    
        public virtual IHP_KIEROWCA IHP_KIEROWCA { get; set; }
    }
}
