//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KpInfohelp
{
    using System;
    using System.Collections.Generic;
    
    public partial class IHP_PARAMETRY
    {
        public int ID_IHP_PARAMETRY { get; set; }
        public string PARAMETR { get; set; }
        public Nullable<int> RODZAJ { get; set; }
        public Nullable<int> ID_GRUPAPARAMETRY { get; set; }
        public string WARTOSC { get; set; }
        public Nullable<int> ID_GRU_PARAMETRY { get; set; }
    }
}
