//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KpInfohelp
{
    using System;
    using System.Collections.Generic;
    
    public partial class IHP_STATUSHISTORIA
    {
        public int ID_IHP_STATUSHISTORIA { get; set; }
        public int ID_IHP_DEFSTATUS { get; set; }
        public byte[] DATAWPISU { get; set; }
        public string OPIS { get; set; }
        public int ID_IHP_POZ { get; set; }
        public int ID_ARIT_ZAM_USERS { get; set; }
        public int ID_IHP_DEFSTATUSZ { get; set; }
    }
}
