//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KpInfohelp
{
    using System;
    using System.Collections.Generic;
    
    public partial class IHP_WAZENIE_USLUGA
    {
        public int ID_IHP_WAZENIE_USLUGA { get; set; }
        public Nullable<System.DateTime> DATACZAS { get; set; }
        public Nullable<int> ID_IHP_KIEROWCA { get; set; }
        public Nullable<int> ID_IHP_SAMOCHOD { get; set; }
        public decimal WAGA { get; set; }
        public Nullable<int> ID_IHP_KONTRAHENT_ARCH { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<int> NRKWIT { get; set; }
        public string NRKWITWEW { get; set; }
        public string KIEROWCA_NAZWA { get; set; }
        public string KONTRAHENT_NAZWA { get; set; }
        public string NRREJ_NAZWA { get; set; }
        public string UWAGI { get; set; }
    }
}
