//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KpInfohelp
{
    using System;
    using System.Collections.Generic;
    
    public partial class IHP_DANEFIRMY
    {
        public int ID_IHP_DANEFIRMY { get; set; }
        public System.DateTime ODDATY { get; set; }
        public Nullable<int> ID_URZSKARB { get; set; }
        public Nullable<int> ID_KRAJ { get; set; }
        public Nullable<int> ID_WOJEWODZTWO { get; set; }
        public string NAZWA_SKROCONA { get; set; }
        public string NAZWA_FIRMY { get; set; }
        public string NIP { get; set; }
        public string REGON { get; set; }
        public string TELEFON { get; set; }
        public string TELEFON2 { get; set; }
        public string FAX { get; set; }
        public string WWW { get; set; }
        public string ULICA { get; set; }
        public string NRDOMU { get; set; }
        public string NRLOKALU { get; set; }
        public string MIEJSCOWOSC { get; set; }
        public string KODPOCZTOWY { get; set; }
        public string POCZTA { get; set; }
        public string EMAIL { get; set; }
    }
}
