//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KpInfohelp
{
    using System;
    using System.Collections.Generic;
    
    public partial class IHP_WYST_GRUPAPARAM
    {
        public int ID_IHP_WYST_GRUPAPARAM { get; set; }
        public int ID_IHP_GRUPAPARAMETRY { get; set; }
        public int ID_IHP_PARAMETRY { get; set; }
    }
}
