//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KpInfohelp
{
    using System;
    using System.Collections.Generic;
    
    public partial class IHP_RODZAJDOK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IHP_RODZAJDOK()
        {
            this.IHP_NAGLDOK = new HashSet<IHP_NAGLDOK>();
        }
    
        public int ID_IHP_RODZAJDOK { get; set; }
        public string OPIS { get; set; }
        public Nullable<int> KIERUNEKMAG { get; set; }
        public string SKROTDOK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IHP_NAGLDOK> IHP_NAGLDOK { get; set; }
    }
}
