//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KpInfohelp
{
    using System;
    using System.Collections.Generic;
    
    public partial class IHP_MASZYNA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IHP_MASZYNA()
        {
            this.IHP_HARMONOGRAM_DZIENNY = new HashSet<IHP_HARMONOGRAM_DZIENNY>();
        }
    
        public int ID_IHP_MASZYNA { get; set; }
        public string NAZWA { get; set; }
        public Nullable<decimal> CENA { get; set; }
        public Nullable<short> AKTYWNY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IHP_HARMONOGRAM_DZIENNY> IHP_HARMONOGRAM_DZIENNY { get; set; }
    }
}
