//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KpInfohelp
{
    using System;
    using System.Collections.Generic;
    
    public partial class IHP_NAGLDOK
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IHP_NAGLDOK()
        {
            this.IHP_POZDOK = new HashSet<IHP_POZDOK>();
        }
    
        public int ID_IHP_NAGLDOK { get; set; }
        public System.DateTime DATADOK { get; set; }
        public int NRDOK { get; set; }
        public string NRDOKWEW { get; set; }
        public Nullable<int> ID_IHP_PRIORYTET { get; set; }
        public decimal SUMAOG { get; set; }
        public int ID_DEFDOK { get; set; }
        public int ID_IHP_KONTRAHENT_ARCH { get; set; }
        public int ID_RODZAJDOK { get; set; }
        public Nullable<int> ID_KH_SUBJECT { get; set; }
        public int ID_IHP_KONTRAHENT { get; set; }
        public Nullable<System.DateTime> DATAWPISU { get; set; }
        public Nullable<System.DateTime> TERMINREALIZ { get; set; }
        public Nullable<int> BLOKADA { get; set; }
        public Nullable<int> STATUS { get; set; }
        public Nullable<int> ILEPOZ { get; set; }
    
        public virtual IHP_KONTRAHENT IHP_KONTRAHENT { get; set; }
        public virtual IHP_KONTRAHENT_ARCH IHP_KONTRAHENT_ARCH { get; set; }
        public virtual IHP_RODZAJDOK IHP_RODZAJDOK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IHP_POZDOK> IHP_POZDOK { get; set; }
    }
}
