//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KpInfohelp
{
    using System;
    using System.Collections.Generic;
    
    public partial class IHP_ZAM_USERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IHP_ZAM_USERS()
        {
            this.IHP_CENNIKHISTORIA = new HashSet<IHP_CENNIKHISTORIA>();
        }
    
        public int ID_IHP_ZAM_USERS { get; set; }
        public Nullable<int> ID_UZYTKOWNIK { get; set; }
        public string LOGIN { get; set; }
        public string HASLO { get; set; }
        public string NAZWISKO_IMIE { get; set; }
        public short AKTYWNY { get; set; }
        public short RESET_HASLA { get; set; }
        public Nullable<short> REJWAGA { get; set; }
        public Nullable<short> USLUGA { get; set; }
        public Nullable<short> KIEROWCY { get; set; }
        public Nullable<short> KARTOTEKI { get; set; }
        public Nullable<short> POJAZDY { get; set; }
        public Nullable<short> KONTRAHENT { get; set; }
        public Nullable<short> DANEFIRMY { get; set; }
        public Nullable<short> REJZAM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IHP_CENNIKHISTORIA> IHP_CENNIKHISTORIA { get; set; }
    }
}
