//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KpInfohelp
{
    using System;
    using System.Collections.Generic;
    
    public partial class IHP_KARTOTEKA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IHP_KARTOTEKA()
        {
            this.IHP_CENNIK = new HashSet<IHP_CENNIK>();
            this.IHP_FOTO = new HashSet<IHP_FOTO>();
            this.IHP_WYSTGRKART = new HashSet<IHP_WYSTGRKART>();
            this.IHP_POZDOK = new HashSet<IHP_POZDOK>();
        }
    
        public int ID_IHP_KARTOTEKA { get; set; }
        public int ID_IHP_STAWKAVAT { get; set; }
        public int ID_IHP_RODZAJKART { get; set; }
        public int ID_IHP_JM { get; set; }
        public string INDEKS { get; set; }
        public string NAZWASKR { get; set; }
        public string NAZWADL { get; set; }
        public string SWW { get; set; }
        public string PKWIU { get; set; }
        public string UWAGI { get; set; }
        public string KODEAN { get; set; }
        public Nullable<int> ID_TOWSUBJECT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IHP_CENNIK> IHP_CENNIK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IHP_FOTO> IHP_FOTO { get; set; }
        public virtual IHP_JM IHP_JM { get; set; }
        public virtual IHP_RODZAJKART IHP_RODZAJKART { get; set; }
        public virtual IHP_STAWKAVAT IHP_STAWKAVAT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IHP_WYSTGRKART> IHP_WYSTGRKART { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IHP_POZDOK> IHP_POZDOK { get; set; }
    }
}
