//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KpInfohelp
{
    using System;
    using System.Collections.Generic;
    
    public partial class IHP_STAWKAVAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IHP_STAWKAVAT()
        {
            this.IHP_KARTOTEKA = new HashSet<IHP_KARTOTEKA>();
        }
    
        public int ID_IHP_STAWKAVAT { get; set; }
        public int WARTOSC { get; set; }
        public string NAZWA { get; set; }
        public short AKTYWNY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IHP_KARTOTEKA> IHP_KARTOTEKA { get; set; }
    }
}
