//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KpInfohelp
{
    using System;
    using System.Collections.Generic;
    
    public partial class IHP_FOTO
    {
        public int ID_IHP_FOTO { get; set; }
        public int ID_IHP_KARTOTEKA { get; set; }
        public Nullable<int> LP { get; set; }
        public string NAMEFILE { get; set; }
        public string NAZWA { get; set; }
    
        public virtual IHP_KARTOTEKA IHP_KARTOTEKA { get; set; }
    }
}
