//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KpInfohelp
{
    using System;
    using System.Collections.Generic;
    
    public partial class IHP_HARMONOGRAM_DZIENNY
    {
        public int ID_IHP_HARMONOGRAM_DZIENNY { get; set; }
        public int ID_IHP_MASZYNA { get; set; }
        public Nullable<System.DateTime> DATA { get; set; }
        public Nullable<System.DateTime> CZASSTART { get; set; }
        public Nullable<System.DateTime> CZASSTOP { get; set; }
        public Nullable<int> ILOSC { get; set; }
        public Nullable<decimal> WAGA { get; set; }
        public int LABELID { get; set; }
        public int ID_IHP_ZAM_USERS { get; set; }
        public string OPIS { get; set; }
        public string TEMAT { get; set; }
        public int ID_KONTRAH { get; set; }
        public Nullable<int> IHP_NAGLDOK { get; set; }
        public string NRDOKZA { get; set; }
        public int ID_KARTOTEKA { get; set; }
    
        public virtual IHP_MASZYNA IHP_MASZYNA { get; set; }
    }
}
