//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KpInfohelp
{
    using System;
    using System.Collections.Generic;
    
    public partial class IHP_WYSTGRKART
    {
        public int ID_IHP_WYSTGRKART { get; set; }
        public int ID_KARTOTEKA { get; set; }
        public int ID_IHP_GRUPAKART { get; set; }
    
        public virtual IHP_GRUPAKART IHP_GRUPAKART { get; set; }
        public virtual IHP_KARTOTEKA IHP_KARTOTEKA { get; set; }
    }
}
