//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KpInfohelp
{
    using System;
    using System.Collections.Generic;
    
    public partial class IHP_KIEROWCA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IHP_KIEROWCA()
        {
            this.IHP_SAMOCHOD = new HashSet<IHP_SAMOCHOD>();
        }
    
        public int ID_IHP_KIEROWCA { get; set; }
        public string NAZWA { get; set; }
        public string TELEFON { get; set; }
        public Nullable<int> ID_IHP_KONTRAHENT { get; set; }
    
        public virtual IHP_KONTRAHENT IHP_KONTRAHENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IHP_SAMOCHOD> IHP_SAMOCHOD { get; set; }
    }
}
