//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KpInfohelp
{
    using System;
    using System.Collections.Generic;
    
    public partial class IHP_DEFCENY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IHP_DEFCENY()
        {
            this.IHP_CENNIK = new HashSet<IHP_CENNIK>();
            this.IHP_KONTRAHENT = new HashSet<IHP_KONTRAHENT>();
        }
    
        public int ID_IHP_DEFCENY { get; set; }
        public string NAZWACENY { get; set; }
        public Nullable<short> ODNETTO { get; set; }
        public Nullable<short> AKTYWNY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IHP_CENNIK> IHP_CENNIK { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IHP_KONTRAHENT> IHP_KONTRAHENT { get; set; }
    }
}
