//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KpInfohelp
{
    using System;
    using System.Collections.Generic;
    
    public partial class IHP_ERPCONNECTOR
    {
        public int ID_IHP_ERPCONNECTOR { get; set; }
        public string ERPNAZWA { get; set; }
        public string SERWER { get; set; }
        public string BAZA { get; set; }
        public string UZYTKOWNIK { get; set; }
        public string HASLO { get; set; }
        public Nullable<int> KARTWSZYSTKO { get; set; }
        public Nullable<int> KARTRODZ { get; set; }
        public string KARTIDRODZ { get; set; }
        public Nullable<int> KARTGRUPA { get; set; }
        public string KARTIDGRUPA { get; set; }
        public Nullable<int> KARTCENNIKI { get; set; }
        public Nullable<int> KONTRAHWSZYSTKO { get; set; }
        public Nullable<int> KONTRAHGRUPA { get; set; }
        public string KONTRAHIDGRUPA { get; set; }
        public int DOKBEZPOSR { get; set; }
        public Nullable<int> DOKWYDANIA { get; set; }
        public Nullable<int> ID_DEFDOK { get; set; }
    }
}
